# Generated by Django 5.2.17 on 2026-08-12 14:02

import oscar.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_analytics_tracked'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='code',
            field=oscar.models.fields.NullCharField(max_length=255, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='code',
            field=oscar.models.fields.NullCharField(max_length=255, unique=True, verbose_name='Code'),
        ),
    ]
