services:
  postgres:
    image: postgres:latest@sha256:ddbc320a9ad558c01c719248108e607eadde92fea799fec799028cfb2fab7319
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  test:
    build: .
    command: env
    links:
      - postgres
    volumes:
      - .:/code
