services:
  postgres:
    image: postgres:latest@sha256:d129b9577d274bb96cbd44d902bdeb1b935c89247d161241e9154cba64e13df4
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  test:
    build: .
    command: env
    links:
      - postgres
    volumes:
      - .:/code
