services:
  postgres:
    image: postgres:latest@sha256:311136771dca6826c3b6e691ebf8cb6e896e165074bc57a728f9619f25f0c4c7
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  test:
    build: .
    command: env
    links:
      - postgres
    volumes:
      - .:/code
